various tiny changes
ralsei/types.pl pull request #16
Opened 2024-03-13 05:10 UTC by omentic

2024-03-13 08:16 UTC, omentic commented
oh also do you want quote toots? i have yet to figure out how mutes work exactly but can pull together a patch for quote toots from existing impls pretty quickly now

2024-04-22 16:04 UTC, ionathanch requested changes
I may make these changes myself later when I have the time, unless you get around to them first

2024-04-22 16:04 UTC, ionathanch commented on app/javascript/flavours/glitch/features/compose/components/search_results.jsx
> -        {statuses}
Is this for the sidebar? Pasting a post URL into the sidebar should still return that post, so this shouldn't be removed

2024-04-22 16:04 UTC, ionathanch commented on app/javascript/flavours/glitch/features/ui/components/navigation_panel.jsx
> -
Remove the `ExploreIcon`, `SearchIcon`, `trendsEnabled` imports so the linter doesn't complain

2024-04-22 16:04 UTC, ionathanch commented on config/locales/en.yml
Are these changes from upstream?

2024-04-22 16:08 UTC, ionathanch commented
We'll hold off on quote toots for this PR

2024-04-22 16:43 UTC, omentic commented
okay, i'll get around to this wednesday (day after finals)

2024-04-22 16:45 UTC, omentic commented on app/javascript/flavours/glitch/features/compose/components/search_results.jsx
> -        {statuses}
i *believe* (will have to check) that posts will still show up in the "all" field
![image](https://github.com/ralsei/types.pl/assets/35242550/422784d2-8b99-4857-815a-3a3464b30301)

2024-04-22 16:48 UTC, omentic commented on config/locales/en.yml
nope, these are my attempts at rewording: https://github.com/ralsei/types.pl/pull/16/commits/a4f08fe03b58ca7c148b47e4235991c109c043d9

i think there... isn't really a not-clunky way to describe unlisted? this as a change is mostly for a VERY specific pet peeve i have where the description is slightly too long and raising the line height

before
![2024-04-22-094625](https://github.com/ralsei/types.pl/assets/35242550/00927dbb-c2b4-4205-9896-ae79ee8c88a2)

after
![2024-04-22-094725](https://github.com/ralsei/types.pl/assets/35242550/ebc50d92-4154-4d18-a9f4-3be96285cd49)

2024-04-22 16:54 UTC, omentic commented
there are other changes i want to pull in, here or as separate PRs:
- mathstodon has a latex patch directly integrated into the compose modal
- treehouse.systems has quote toots (no strong feelings on this, but displaying quote toots properly at least seems nice)
- catstodon has a fix for like propagation: https://git.kescher.at/CatCatNya/catstodon/commit/16be9e975b495c43035cda4e82ead2cb5374f700
- neuromatch.social has a patch to pull in replies from other instances: https://neuromatch.social/@jonny/112307981094627966

the ui revamp broke oatstodon.css also... i really need to fix it, that'll probably be tacked onto here

2024-04-22 17:08 UTC, ionathanch commented on config/locales/en.yml
oh these are fine, the ones I was referring to looks like are from the "reduce changes from upstream" commit? b68aab7a108776e9fe522a8cb2604a20a49bc833
I can't tell if you missed one or if this is how github is showing that it's reverting back to what it used to be or whatever

2024-04-22 17:14 UTC, omentic commented
notes to self: other things i would like to do that are more involved, so depend on how much time i'm able to put into them / actually getting the build system to function:
- username renaming and post migration. these kind of go hand in hand: https://types.pl/@jj/111973561247740433. as i understand it it requires deep enough knowledge of mastodon internals that i do not think this is super doable *well* unless a patch already exists. (it would be doable poorly. by grepping for all internal usages of usernames in url accesses and replacing those with accesses by actor ids. but)
- mutes collapsing instead of removing replies by default. i just haven't had the time to see how doable it is yet
- fix the other themes. i just need a working build environment
- play around with implementing a bubble timeline a la akkoma? conceptually this is pretty simple, you just hijack and filter the firehouse. the tricky part will be adding support in settings and what not
- see how doable reverting the icons and particularly bringing back the animations are. (they still exist!! in picture modals.)  also remove the threaded mode icon

2024-04-22 17:17 UTC, omentic commented on config/locales/en.yml
hmm, i'll double-check later but iirc yeah they are

2024-04-26 02:32 UTC, omentic commented on config/locales/en.yml
yup

2024-04-26 07:38 UTC, omentic commented
this is about everything simple that i can do without a build environment. i'd like to make the cybre.space flavour not a separate skin from the "default" skin, but i can't do that without testing it out as i'm not quite sure how it works

2024-04-29 20:19 UTC, omentic commented
grr i keep finding tiny little oatstodon css issues. that hopefully is the last of them

2024-05-01 19:51 UTC, omentic commented
okay, this is done, for real. everything else will be separate

2024-06-23 17:59 UTC, merged

2024-06-23 19:02 UTC, ionathanch commented
cybrespace theme broken don't know why. Going to `/settings/flavours/cybrespace`  gives the "We're sorry, but something went wrong on our end." page and `journalctl -u mastodon-web` only seems to say this:

```
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88]      5:   = render 'shared/error_messages', object: current_user
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88]      6:
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88]      7:   - Themes.instance.flavour(@selected)['screenshot'].each do |screenshot|
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88]      8:     %img.flavour-screen{ src: frontend_asset_url(screenshot), alt: '' }
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88]      9:
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88]     10:   .flavour-description
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88]     11:     = t "flavours.#{@selected}.description", default: ''
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88]
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88] app/helpers/routing_helper.rb:28:in `frontend_asset_path'
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88] app/helpers/routing_helper.rb:32:in `frontend_asset_url'
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88] app/views/settings/flavours/show.html.haml:8
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88] app/views/settings/flavours/show.html.haml:7:in `each'
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88] app/views/settings/flavours/show.html.haml:7
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88] app/views/settings/flavours/show.html.haml:4
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88] app/controllers/concerns/localized.rb:11:in `set_locale'
Jun 23 18:52:04 types bundle[3621]: [c534eece-a9ec-45d5-9808-cdc619ca9d88] lib/mastodon/rack_middleware.rb:9:in `call'
```

but cybrespace-preview.png is correctly located

2024-06-23 21:57 UTC, ionathanch commented
`RAILS_ENV=production bundle exec rails assets:precompile` is failing to put the screenshot into `public/packs/media/flavours/cybrespace/images` for unknown reasons so I'm going to just remove the screenshot link for now and come back to it later